# TCL File Generated by Component Editor 18.1
# Thu Dec 17 15:01:34 CET 2020
# DO NOT MODIFY


# 
# D5M_top "D5M_top" v1.0
#  2020.12.17.15:01:34
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module D5M_top
# 
set_module_property DESCRIPTION ""
set_module_property NAME D5M_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME D5M_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL D5M_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file D5M_top.vhdl VHDL PATH ip/D5M_top/D5M_top.vhdl
add_fileset_file AvalonMasterwrite.vhdl VHDL PATH ip/D5M_top/AvalonMasterwrite.vhdl
add_fileset_file AvalonSlave.vhdl VHDL PATH ip/D5M_top/AvalonSlave.vhdl
add_fileset_file MyFIFO.vhd VHDL PATH ip/D5M_top/MyFIFO.vhd
add_fileset_file clk_gen.vhd VHDL PATH ip/D5M_top/clk_gen.vhd
add_fileset_file cam_interface_v2.vhd VHDL PATH ip/D5M_top/cam_interface_v2.vhd
add_fileset_file interface_fifo.vhd VHDL PATH ../../../D5M_V2/interface_fifo.vhd


# 
# parameters
# 
add_parameter AvalonAddressDepth INTEGER 64
set_parameter_property AvalonAddressDepth DEFAULT_VALUE 64
set_parameter_property AvalonAddressDepth DISPLAY_NAME AvalonAddressDepth
set_parameter_property AvalonAddressDepth TYPE INTEGER
set_parameter_property AvalonAddressDepth UNITS None
set_parameter_property AvalonAddressDepth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AvalonAddressDepth HDL_PARAMETER true
add_parameter AvalonBustDepth INTEGER 7 ""
set_parameter_property AvalonBustDepth DEFAULT_VALUE 7
set_parameter_property AvalonBustDepth DISPLAY_NAME AvalonBustDepth
set_parameter_property AvalonBustDepth TYPE INTEGER
set_parameter_property AvalonBustDepth UNITS None
set_parameter_property AvalonBustDepth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AvalonBustDepth DESCRIPTION ""
set_parameter_property AvalonBustDepth HDL_PARAMETER true
add_parameter AvalonBustN INTEGER 16 ""
set_parameter_property AvalonBustN DEFAULT_VALUE 16
set_parameter_property AvalonBustN DISPLAY_NAME AvalonBustN
set_parameter_property AvalonBustN TYPE INTEGER
set_parameter_property AvalonBustN UNITS None
set_parameter_property AvalonBustN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AvalonBustN DESCRIPTION ""
set_parameter_property AvalonBustN HDL_PARAMETER true
add_parameter AvalonDataDepth INTEGER 32 ""
set_parameter_property AvalonDataDepth DEFAULT_VALUE 32
set_parameter_property AvalonDataDepth DISPLAY_NAME AvalonDataDepth
set_parameter_property AvalonDataDepth TYPE INTEGER
set_parameter_property AvalonDataDepth UNITS None
set_parameter_property AvalonDataDepth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AvalonDataDepth DESCRIPTION ""
set_parameter_property AvalonDataDepth HDL_PARAMETER true
add_parameter LcdNPixel INTEGER 76800 ""
set_parameter_property LcdNPixel DEFAULT_VALUE 76800
set_parameter_property LcdNPixel DISPLAY_NAME LcdNPixel
set_parameter_property LcdNPixel TYPE INTEGER
set_parameter_property LcdNPixel UNITS None
set_parameter_property LcdNPixel ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LcdNPixel DESCRIPTION ""
set_parameter_property LcdNPixel HDL_PARAMETER true
add_parameter PixelCountDepth INTEGER 20 ""
set_parameter_property PixelCountDepth DEFAULT_VALUE 20
set_parameter_property PixelCountDepth DISPLAY_NAME PixelCountDepth
set_parameter_property PixelCountDepth TYPE INTEGER
set_parameter_property PixelCountDepth UNITS None
set_parameter_property PixelCountDepth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PixelCountDepth DESCRIPTION ""
set_parameter_property PixelCountDepth HDL_PARAMETER true
add_parameter PixelDepth INTEGER 16
set_parameter_property PixelDepth DEFAULT_VALUE 16
set_parameter_property PixelDepth DISPLAY_NAME PixelDepth
set_parameter_property PixelDepth TYPE INTEGER
set_parameter_property PixelDepth UNITS None
set_parameter_property PixelDepth HDL_PARAMETER true
add_parameter FifoCountDepth INTEGER 7 ""
set_parameter_property FifoCountDepth DEFAULT_VALUE 7
set_parameter_property FifoCountDepth DISPLAY_NAME FifoCountDepth
set_parameter_property FifoCountDepth TYPE INTEGER
set_parameter_property FifoCountDepth UNITS None
set_parameter_property FifoCountDepth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FifoCountDepth DESCRIPTION ""
set_parameter_property FifoCountDepth HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point sl
# 
add_interface sl avalon end
set_interface_property sl addressUnits WORDS
set_interface_property sl associatedClock clock
set_interface_property sl associatedReset reset
set_interface_property sl bitsPerSymbol 8
set_interface_property sl burstOnBurstBoundariesOnly false
set_interface_property sl burstcountUnits WORDS
set_interface_property sl explicitAddressSpan 0
set_interface_property sl holdTime 0
set_interface_property sl linewrapBursts false
set_interface_property sl maximumPendingReadTransactions 0
set_interface_property sl maximumPendingWriteTransactions 0
set_interface_property sl readLatency 0
set_interface_property sl readWaitTime 1
set_interface_property sl setupTime 0
set_interface_property sl timingUnits Cycles
set_interface_property sl writeWaitTime 0
set_interface_property sl ENABLED true
set_interface_property sl EXPORT_OF ""
set_interface_property sl PORT_NAME_MAP ""
set_interface_property sl CMSIS_SVD_VARIABLES ""
set_interface_property sl SVD_ADDRESS_GROUP ""

add_interface_port sl address_SL address Input 4
add_interface_port sl write_SL write Input 1
add_interface_port sl read_SL read Input 1
add_interface_port sl writedata_SL writedata Input 8
add_interface_port sl readdata_SL readdata Output 8
set_interface_assignment sl embeddedsw.configuration.isFlash 0
set_interface_assignment sl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment sl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment sl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point cam_interface
# 
add_interface cam_interface conduit end
set_interface_property cam_interface associatedClock ""
set_interface_property cam_interface associatedReset reset
set_interface_property cam_interface ENABLED true
set_interface_property cam_interface EXPORT_OF ""
set_interface_property cam_interface PORT_NAME_MAP ""
set_interface_property cam_interface CMSIS_SVD_VARIABLES ""
set_interface_property cam_interface SVD_ADDRESS_GROUP ""

add_interface_port cam_interface data data Input 12
add_interface_port cam_interface pclk pclk Input 1
add_interface_port cam_interface fval fval Input 1
add_interface_port cam_interface lval lval Input 1
add_interface_port cam_interface mclk mclk Output 1
add_interface_port cam_interface cam_reset cam_reset Output 1


# 
# connection point avalon_ma
# 
add_interface avalon_ma avalon start
set_interface_property avalon_ma addressUnits SYMBOLS
set_interface_property avalon_ma associatedClock clock
set_interface_property avalon_ma associatedReset reset
set_interface_property avalon_ma bitsPerSymbol 8
set_interface_property avalon_ma burstOnBurstBoundariesOnly false
set_interface_property avalon_ma burstcountUnits WORDS
set_interface_property avalon_ma doStreamReads false
set_interface_property avalon_ma doStreamWrites false
set_interface_property avalon_ma holdTime 0
set_interface_property avalon_ma linewrapBursts false
set_interface_property avalon_ma maximumPendingReadTransactions 0
set_interface_property avalon_ma maximumPendingWriteTransactions 0
set_interface_property avalon_ma readLatency 0
set_interface_property avalon_ma readWaitTime 1
set_interface_property avalon_ma setupTime 0
set_interface_property avalon_ma timingUnits Cycles
set_interface_property avalon_ma writeWaitTime 0
set_interface_property avalon_ma ENABLED true
set_interface_property avalon_ma EXPORT_OF ""
set_interface_property avalon_ma PORT_NAME_MAP ""
set_interface_property avalon_ma CMSIS_SVD_VARIABLES ""
set_interface_property avalon_ma SVD_ADDRESS_GROUP ""

add_interface_port avalon_ma waitrequest_MA waitrequest Input 1
add_interface_port avalon_ma write_MA write Output 1
add_interface_port avalon_ma read_MA read Output 1
add_interface_port avalon_ma beginburst_MA beginbursttransfer Output 1
add_interface_port avalon_ma burstcount_MA burstcount Output avalonbustdepth
add_interface_port avalon_ma address_MA address Output avalonaddressdepth
add_interface_port avalon_ma writedata_MA writedata Output avalondatadepth
add_interface_port avalon_ma readdata_MA readdata Input avalondatadepth
add_interface_port avalon_ma readDataVa_MA readdatavalid Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset nReset reset_n Input 1

